---
title: "Dashboard shiny R"
output: html_document
date: "2024-10-19"
---

#Bibliotecas a serem instaladas
```{r}
install.packages("dplyr")
install.packages("ggplot2")

```

#Chamando as Bibliotecas
```{r}
library(ggplot2)
library(plotly)
```


```{r}
library(dplyr)
```


#Importando os dados:
```{r}
library(readr)
dados <- read_csv("dados_shiny_2022081822.csv")
View(dados_shiny_2022081822)
```
#filtro teste
```{r}
modelo <- 'corolla xei 16v' 
uf <- c('mt', 'se')

dados_select <- dados %>% filter(MODELO == modelo &
                        UF %in% uf)

```


```{r}
theme_set(theme_classic())
```

Valor medio ao longo do tempo

```{r}
mediana_data <- dados_select %>%
  group_by(DATA_COLETA_METADADOS, UF) %>%
    summarise(mediaValor = median(VALOR))


ggplotly(
  mediana_data %>%
  ggplot() + 
    geom_line(aes(x = DATA_COLETA_METADADOS, y = mediaValor,
                  group = UF, color = UF), size = 1) + ggtitle("Média Valor") +
  scale_color_brewer(palette = "Dark2")
)
```
Variação de valores por UF
```{r}
ggplotly(
  dados_select %>%
  ggplot() + 
  geom_boxplot(aes(x = UF, y = VALOR, fill = UF)) +
  ggtitle('Variação de preço por UF') +
  scale_fill_brewer(palette = "Dark2")
)

```

Variação KM, valor e UF

```{r}
ggplotly(
  dados_select %>%
  ggplot() + 
  geom_point(aes(x = QUILOMETRAGEM, y = VALOR, color = UF)) +
  ggtitle("Distribuição do VALOR e KM por UF") +
  scale_color_brewer(palette = "Dark2")
)
```
Frequencias dos cambios dos auotmoveis

```{r}
freq_cambio <- dados_select %>%
  group_by(CÂMBIO) %>%
  summarise(qtd = n()) %>%
  mutate(prop = qtd / sum(qtd) * 100) %>%
  mutate(ypos = cumsum(prop) - 0.5 * prop)
  
freq_cambio %>%
  ggplot(aes(x = '', y = prop, fill = CÂMBIO)) +
  geom_bar(stat = 'identity') +
  coord_polar('y', start = 0) +
  theme_void() + theme(legend.position = "none") +
  geom_text(aes(y = ypos,
                label = paste(CÂMBIO, '\n', round(prop, 2), '%')),
            color = 'white', size = 6) +
  ggtitle('Quantidade por câmbio') +
  scale_fill_brewer(palette = "Dark2")
  
  
```
#Frequencia de valor por tipo de anuncio
```{r}
dados_select %>%
  ggplot() + 
  geom_boxplot(aes(x = TIPO_ANUNCIO, y = VALOR, fill = UF)) +
  ggtitle('Variação de preço por UF') +
  scale_fill_brewer(palette = "Dark2")
```
#Frequencia por tipo de direção

```{r}
freq_direcao <- dados_select %>%
  group_by(DIREÇÃO) %>%
  summarise(qtd = n()) %>%
  mutate(prop = qtd / sum(qtd) * 100) %>%
  mutate(ypos = cumsum(prop) - 0.5 * prop)
  
freq_direcao %>%
  ggplot(aes(x = '', y = prop, fill = DIREÇÃO)) +
  geom_bar(stat = 'identity') +
  coord_polar('y', start = 0) +
  theme_void() + theme(legend.position = "none") +
  geom_text(aes(y = ypos,
                label = paste(DIREÇÃO, '\n', round(prop, 1), '%')),
            color = 'white', size = 6) +
  ggtitle('Quantidade por tipo de direção') +
  scale_fill_brewer(palette = "Dark2")

```


#Frequencia de anuncio por COR
```{r}
ggplotly(
  dados_select %>%
  group_by(COR) %>%
  summarise(QTD = n()) %>%
  ggplot() + 
    geom_bar(aes(x = reorder(COR, QTD), y = QTD, fill = QTD), stat = 'identity') +
  xlab('COR') + ggtitle('Quantidade por Cor') +
  theme(legend.position = 'none')
    
)
  
```

